import type { GameMetrics, IndicatorInfo, IndicatorKey, MetricBounds, MetricGroup, MetricKey } from '@/types';

/**
 * Valores iniciais (Jan/2027), calibrados com dados públicos de 2023–2025.
 * Indicadores principais seguem a tabela do GDD §3.1.
 */
export const INITIAL_METRICS: GameMetrics = {
  gdp: 11.0, // GDD §3.1 (IBGE: PIB 2024 ≈ R$ 11,7 tri nominal)
  gdpGrowth: 2.2, // IBGE/BCB: crescimento 2025 ≈ 2,2%
  potentialGrowth: 2.0, // estimativas IFI/BCB para PIB potencial ≈ 2%
  inflation: 4.5, // GDD §3.1 (teto da meta 4,5%)
  unemployment: 7.8, // GDD §3.1 (PNAD Contínua)
  exchangeRate: 5.4, // GDD §3.1 (BCB PTAX)
  debt: 74, // GDD §3.1 (Tesouro: DBGG ≈ 74–77% do PIB)
  selic: 12.25, // Copom, dez/2024
  primaryBalance: -0.4, // Tesouro: déficit primário 2024 ≈ 0,4% do PIB
  foreignInvestment: 71, // BCB: IDP 2024 ≈ US$ 71 bi
  hdi: 0.76, // PNUD: IDH 2022 = 0,760
  gini: 0.518, // IBGE PNAD 2023
  poverty: 27.4, // IBGE SIS 2023
  healthCoverage: 76, // Ministério da Saúde: cobertura da atenção primária ≈ 76%
  ideb: 5.1, // INEP: média aproximada dos três ciclos (2023)
  housingDeficit: 6.2, // Fundação João Pinheiro 2022: 6,2 milhões de domicílios
  homicideRate: 21.2, // Atlas da Violência (IPEA) 2025
  securityTrust: 45, // pesquisas de opinião (Datafolha/FBSP)
  sanitation: 56, // SNIS 2022: 56% com coleta de esgoto
  renewableEnergy: 88, // EPE BEN 2024: matriz elétrica ≈ 88% renovável
  digitalConnectivity: 92.5, // IBGE PNAD TIC 2023
  infrastructureKm: 0, // contador do mandato
  deforestation: 6288, // INPE PRODES 2024 (Amazônia Legal)
  co2Emissions: 2300, // SEEG 2023: ≈ 2,3 Gt CO₂e
  waterReserves: 65, // ONS/ANA: índice médio de reservatórios
  prestige: 60, // índice próprio do jogo
  tradeBalance: 74.6, // MDIC 2024: US$ 74,6 bi
  ideologyEconomic: 0, // substituído pela ideologia do candidato na posse
  ideologySocial: 0,
};

export const METRIC_KEYS: readonly MetricKey[] = Object.keys(INITIAL_METRICS) as MetricKey[];

/** Limites físicos/plausíveis de cada métrica (clamp do engine). */
export const METRIC_BOUNDS: Record<MetricKey, MetricBounds> = {
  gdp: { min: 5, max: 25 },
  gdpGrowth: { min: -10, max: 10 },
  potentialGrowth: { min: -1, max: 5 },
  inflation: { min: -2, max: 40 },
  unemployment: { min: 2, max: 25 },
  exchangeRate: { min: 2, max: 12 },
  debt: { min: 30, max: 160 },
  selic: { min: 2, max: 30 },
  primaryBalance: { min: -8, max: 5 },
  foreignInvestment: { min: 5, max: 150 },
  hdi: { min: 0.6, max: 0.95 },
  gini: { min: 0.35, max: 0.65 },
  poverty: { min: 3, max: 60 },
  healthCoverage: { min: 40, max: 100 },
  ideb: { min: 2, max: 9 },
  housingDeficit: { min: 0.5, max: 12 },
  homicideRate: { min: 3, max: 45 },
  securityTrust: { min: 0, max: 100 },
  sanitation: { min: 30, max: 100 },
  renewableEnergy: { min: 50, max: 100 },
  digitalConnectivity: { min: 70, max: 100 },
  infrastructureKm: { min: 0, max: 50000 },
  deforestation: { min: 0, max: 30000 },
  co2Emissions: { min: 800, max: 4000 },
  waterReserves: { min: 0, max: 100 },
  prestige: { min: 0, max: 100 },
  tradeBalance: { min: -80, max: 200 },
  ideologyEconomic: { min: -100, max: 100 },
  ideologySocial: { min: -100, max: 100 },
};

export const INDICATOR_INFO: Record<IndicatorKey, IndicatorInfo> = {
  approval: {
    label: 'Aprovação Popular',
    shortLabel: 'Aprovação',
    icon: '📊',
    prefix: '',
    suffix: '%',
    decimals: 0,
    polarity: 1,
    group: 'politics',
    description: 'Média ponderada da aprovação de cada setor da sociedade. Abaixo de 15%, com base fraca, há risco de impeachment.',
    source: 'Datafolha / Quaest',
  },
  congressSupport: {
    label: 'Base Aliada no Congresso',
    shortLabel: 'Congresso',
    icon: '⚖️',
    prefix: '',
    suffix: '%',
    decimals: 0,
    polarity: 1,
    group: 'politics',
    description: 'Parcela do Congresso que apoia o governo. Leis ordinárias exigem 50%+; PECs, 60%+. Base fraca abre espaço para CPIs.',
    source: 'Câmara dos Deputados',
  },
  gdp: {
    label: 'PIB',
    shortLabel: 'PIB',
    icon: '💰',
    prefix: 'R$ ',
    suffix: ' tri',
    decimals: 2,
    polarity: 1,
    group: 'economy',
    description: 'Produto Interno Bruto anual em trilhões de reais (preços constantes). Cresce conforme o ritmo da economia.',
    source: 'IBGE',
  },
  gdpGrowth: {
    label: 'Crescimento do PIB',
    shortLabel: 'Crescimento',
    icon: '📈',
    prefix: '',
    suffix: '%',
    decimals: 1,
    polarity: 1,
    group: 'economy',
    description: 'Ritmo anualizado de crescimento real da economia. Juros altos freiam; investimento e confiança aceleram.',
    source: 'IBGE / BCB',
  },
  potentialGrowth: {
    label: 'Crescimento Potencial',
    shortLabel: 'Cresc. futuro',
    icon: '🧭',
    prefix: '',
    suffix: '%',
    decimals: 1,
    polarity: 1,
    group: 'economy',
    description: 'Quanto a economia consegue crescer sem gerar inflação. Só sobe com reformas, educação e infraestrutura.',
    source: 'IFI / BCB',
  },
  inflation: {
    label: 'Inflação (IPCA 12m)',
    shortLabel: 'Inflação',
    icon: '🛒',
    prefix: '',
    suffix: '%',
    decimals: 1,
    polarity: -1,
    group: 'economy',
    description: 'Alta de preços acumulada em 12 meses. A meta é 3% (tolerância até 4,5%). Corrói a renda dos mais pobres.',
    source: 'IBGE',
  },
  unemployment: {
    label: 'Desemprego',
    shortLabel: 'Desemprego',
    icon: '👥',
    prefix: '',
    suffix: '%',
    decimals: 1,
    polarity: -1,
    group: 'economy',
    description: 'Taxa de desocupação da força de trabalho. Cai quando a economia cresce acima do potencial.',
    source: 'IBGE PNAD Contínua',
  },
  exchangeRate: {
    label: 'Dólar',
    shortLabel: 'Dólar',
    icon: '💵',
    prefix: 'R$ ',
    suffix: '',
    decimals: 2,
    polarity: -1,
    group: 'economy',
    description: 'Cotação do dólar em reais. Sobe com risco fiscal e juros baixos; dólar alto pressiona a inflação mas ajuda exportadores.',
    source: 'BCB PTAX',
  },
  debt: {
    label: 'Dívida Pública',
    shortLabel: 'Dívida/PIB',
    icon: '🏦',
    prefix: '',
    suffix: '% PIB',
    decimals: 1,
    polarity: -1,
    group: 'economy',
    description: 'Dívida bruta do governo em relação ao PIB. Cresce com déficits e juros altos; acima de 90% assusta o mercado.',
    source: 'Tesouro Nacional',
  },
  selic: {
    label: 'Taxa Selic',
    shortLabel: 'Juros',
    icon: '🏛️',
    prefix: '',
    suffix: '%',
    decimals: 2,
    polarity: 0,
    group: 'economy',
    description: 'Juro básico da economia. Subir controla a inflação mas freia o crescimento e encarece a dívida.',
    source: 'Copom / BCB',
  },
  primaryBalance: {
    label: 'Resultado Primário',
    shortLabel: 'Contas públicas',
    icon: '🧾',
    prefix: '',
    suffix: '% PIB',
    decimals: 1,
    polarity: 1,
    group: 'economy',
    description: 'Receitas menos despesas do governo, sem contar juros. Negativo significa déficit, que aumenta a dívida.',
    source: 'Tesouro Nacional',
  },
  foreignInvestment: {
    label: 'Investimento Estrangeiro',
    shortLabel: 'Invest. estrangeiro',
    icon: '🌐',
    prefix: 'US$ ',
    suffix: ' bi',
    decimals: 0,
    polarity: 1,
    group: 'foreign',
    description: 'Investimento direto estrangeiro anual. Cresce com boas relações internacionais e confiança do mercado.',
    source: 'BCB',
  },
  hdi: {
    label: 'IDH',
    shortLabel: 'IDH',
    icon: '🌱',
    prefix: '',
    suffix: '',
    decimals: 3,
    polarity: 1,
    group: 'social',
    description: 'Índice de Desenvolvimento Humano: combina renda, saúde e educação.',
    source: 'PNUD',
  },
  gini: {
    label: 'Índice de Gini',
    shortLabel: 'Desigualdade',
    icon: '⚖️',
    prefix: '',
    suffix: '',
    decimals: 3,
    polarity: -1,
    group: 'social',
    description: 'Desigualdade de renda (0 = igualdade total, 1 = desigualdade máxima). O Brasil está entre os mais desiguais.',
    source: 'IBGE',
  },
  poverty: {
    label: 'Taxa de Pobreza',
    shortLabel: 'Pobreza',
    icon: '🏚️',
    prefix: '',
    suffix: '%',
    decimals: 1,
    polarity: -1,
    group: 'social',
    description: 'População abaixo da linha de pobreza. Sensível a emprego, inflação e programas sociais.',
    source: 'IBGE SIS',
  },
  healthCoverage: {
    label: 'Cobertura do SUS',
    shortLabel: 'Saúde',
    icon: '🏥',
    prefix: '',
    suffix: '%',
    decimals: 1,
    polarity: 1,
    group: 'social',
    description: 'Cobertura da atenção primária à saúde (equipes de Saúde da Família).',
    source: 'Ministério da Saúde / DataSUS',
  },
  ideb: {
    label: 'IDEB',
    shortLabel: 'IDEB',
    icon: '📚',
    prefix: '',
    suffix: '',
    decimals: 2,
    polarity: 1,
    group: 'social',
    description: 'Índice de Desenvolvimento da Educação Básica (0–10). Melhora lentamente com investimento contínuo.',
    source: 'INEP',
  },
  housingDeficit: {
    label: 'Déficit Habitacional',
    shortLabel: 'Moradia',
    icon: '🏠',
    prefix: '',
    suffix: ' mi',
    decimals: 2,
    polarity: -1,
    group: 'social',
    description: 'Milhões de domicílios em situação precária, coabitação ou ônus excessivo com aluguel.',
    source: 'Fundação João Pinheiro',
  },
  homicideRate: {
    label: 'Taxa de Homicídios',
    shortLabel: 'Homicídios',
    icon: '🚨',
    prefix: '',
    suffix: '/100 mil',
    decimals: 1,
    polarity: -1,
    group: 'security',
    description: 'Homicídios por 100 mil habitantes por ano.',
    source: 'Atlas da Violência (IPEA/FBSP)',
  },
  securityTrust: {
    label: 'Confiança na Segurança',
    shortLabel: 'Confiança na polícia',
    icon: '🛡️',
    prefix: '',
    suffix: '',
    decimals: 0,
    polarity: 1,
    group: 'security',
    description: 'Confiança da população nas forças de segurança (0–100).',
    source: 'Fórum Brasileiro de Segurança Pública',
  },
  sanitation: {
    label: 'Saneamento',
    shortLabel: 'Saneamento',
    icon: '🚰',
    prefix: '',
    suffix: '%',
    decimals: 1,
    polarity: 1,
    group: 'infrastructure',
    description: 'Domicílios atendidos por coleta de esgoto. O Marco do Saneamento prevê 90% até 2033.',
    source: 'SNIS',
  },
  renewableEnergy: {
    label: 'Energia Renovável',
    shortLabel: 'Renovável',
    icon: '⚡',
    prefix: '',
    suffix: '%',
    decimals: 1,
    polarity: 1,
    group: 'infrastructure',
    description: 'Participação de fontes renováveis na matriz elétrica.',
    source: 'EPE',
  },
  digitalConnectivity: {
    label: 'Conectividade Digital',
    shortLabel: 'Internet',
    icon: '📶',
    prefix: '',
    suffix: '%',
    decimals: 1,
    polarity: 1,
    group: 'infrastructure',
    description: 'Domicílios com acesso à internet.',
    source: 'IBGE PNAD TIC',
  },
  infrastructureKm: {
    label: 'Obras Entregues',
    shortLabel: 'Obras',
    icon: '🛤️',
    prefix: '',
    suffix: ' km',
    decimals: 0,
    polarity: 1,
    group: 'infrastructure',
    description: 'Quilômetros de rodovias e ferrovias entregues neste governo.',
    source: 'DNIT / Ministério dos Transportes',
  },
  deforestation: {
    label: 'Desmatamento na Amazônia',
    shortLabel: 'Desmatamento',
    icon: '🌳',
    prefix: '',
    suffix: ' km²',
    decimals: 0,
    polarity: -1,
    group: 'environment',
    description: 'Área desmatada por ano na Amazônia Legal. Alto desmatamento gera pressão internacional.',
    source: 'INPE PRODES',
  },
  co2Emissions: {
    label: 'Emissões de CO₂',
    shortLabel: 'Emissões',
    icon: '🏭',
    prefix: '',
    suffix: ' Mt',
    decimals: 0,
    polarity: -1,
    group: 'environment',
    description: 'Emissões brutas anuais de gases de efeito estufa (milhões de toneladas de CO₂ equivalente).',
    source: 'SEEG',
  },
  waterReserves: {
    label: 'Reservas Hídricas',
    shortLabel: 'Água',
    icon: '💧',
    prefix: '',
    suffix: '',
    decimals: 0,
    polarity: 1,
    group: 'environment',
    description: 'Nível médio dos reservatórios (0–100). Secas reduzem; abaixo de 30 há risco de racionamento.',
    source: 'ONS / ANA',
  },
  prestige: {
    label: 'Prestígio Internacional',
    shortLabel: 'Prestígio',
    icon: '🌍',
    prefix: '',
    suffix: '',
    decimals: 0,
    polarity: 1,
    group: 'foreign',
    description: 'Influência e reputação do Brasil no mundo (0–100).',
    source: 'Itamaraty / índice próprio',
  },
  tradeBalance: {
    label: 'Balança Comercial',
    shortLabel: 'Saldo comercial',
    icon: '🚢',
    prefix: 'US$ ',
    suffix: ' bi',
    decimals: 1,
    polarity: 1,
    group: 'foreign',
    description: 'Exportações menos importações no ano. Dólar alto e commodities em alta aumentam o saldo.',
    source: 'MDIC',
  },
  ideologyEconomic: {
    label: 'Linha Econômica do Governo',
    shortLabel: 'Linha econômica',
    icon: '🧭',
    prefix: '',
    suffix: '',
    decimals: 0,
    polarity: 0,
    group: 'politics',
    description: 'Para onde o governo puxa a economia: estatismo e redistribuição (esquerda) ou mercado e privatizações (direita). Muda com as suas escolhas.',
    source: 'Índice próprio do jogo',
  },
  ideologySocial: {
    label: 'Linha nos Costumes',
    shortLabel: 'Linha nos costumes',
    icon: '⚖️',
    prefix: '',
    suffix: '',
    decimals: 0,
    polarity: 0,
    group: 'politics',
    description: 'Posição do governo em pautas de costumes, segurança e direitos: progressista ou conservadora. Muda com as suas escolhas.',
    source: 'Índice próprio do jogo',
  },
};

/** Indicadores principais sempre visíveis no painel (GDD §3.1). */
export const PRIMARY_INDICATORS: readonly IndicatorKey[] = [
  'approval',
  'gdp',
  'inflation',
  'unemployment',
  'exchangeRate',
  'debt',
  'congressSupport',
];

export const METRIC_GROUP_LABELS: Record<MetricGroup, string> = {
  economy: 'Economia',
  social: 'Social',
  security: 'Segurança',
  infrastructure: 'Infraestrutura',
  environment: 'Meio Ambiente',
  foreign: 'Relações Exteriores',
  politics: 'Política',
};

/** Métricas secundárias agrupadas para o painel detalhado (GDD §3.2). */
export const SECONDARY_METRIC_GROUPS: ReadonlyArray<{ group: MetricGroup; metrics: readonly MetricKey[] }> = [
  { group: 'economy', metrics: ['gdpGrowth', 'potentialGrowth', 'selic', 'primaryBalance'] },
  { group: 'social', metrics: ['hdi', 'gini', 'poverty', 'healthCoverage', 'ideb', 'housingDeficit'] },
  { group: 'security', metrics: ['homicideRate', 'securityTrust'] },
  { group: 'infrastructure', metrics: ['sanitation', 'renewableEnergy', 'digitalConnectivity', 'infrastructureKm'] },
  { group: 'environment', metrics: ['deforestation', 'co2Emissions', 'waterReserves'] },
  { group: 'foreign', metrics: ['prestige', 'tradeBalance', 'foreignInvestment'] },
];

/** Aprovação inicial de referência (GDD §3.1), antes das afinidades do candidato. */
export const INITIAL_APPROVAL = 45;

/** Base aliada inicial de referência (GDD §3.1), antes do resultado da eleição. */
export const INITIAL_CONGRESS_SUPPORT = 55;
